/**
 * Type definitions for summary-related data structures
 */

/**
 * Meeting summary generated by LLM
 */
export interface Summary {
  /** Meeting title/name */
  meetingTitle: string;
  /** Generated summary content (markdown format) or null if not yet generated */
  summary: string | null;
}

/**
 * Options for generating a summary
 */
export interface SummaryOptions {
  /** Custom user prompt to guide summary generation */
  custom_prompt?: string;
  /** System prompt for LLM behavior */
  system_prompt?: string;
}

/**
 * Export format options
 */
export type ExportFormat = 'json' | 'markdown' | 'pdf';
