name: Lint Frontend

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'frontend/**'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

permissions:
  contents: write

jobs:
  lint:
    name: Run ESLint, Prettier, Stylelint (Auto-Fix + Push)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Auto-fix ESLint issues
        run: npx eslint src --fix

      - name: Auto-fix Prettier issues
        run: npx prettier --write .

      - name: Auto-fix Stylelint issues
        run: npm run lint:css:fix

      - name: Create PR with lint fixes (if any)
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Check if there are any changes to commit
          if git diff --quiet && git diff --cached --quiet; then
            echo "No linting changes needed"
            exit 0
          fi

          # Create a unique branch name for the lint fixes
          LINT_BRANCH="auto-lint-fixes-$(date +%s)"
          
          git checkout -b $LINT_BRANCH
          git add .
          git commit -m "style: auto-fix linting issues

          - Fixed ESLint issues
          - Applied Prettier formatting
          - Fixed Stylelint issues
          
          🤖 Automated fixes by GitHub Actions"
          
          git push origin $LINT_BRANCH
          
          # Create PR
          gh pr create \
            --title "🤖 Auto-fix linting issues" \
            --body "Automated linting fixes generated by GitHub Actions.

          ## Changes
          - ✅ ESLint auto-fixes applied
          - ✅ Prettier formatting applied  
          - ✅ Stylelint issues resolved

          This PR was automatically created to fix linting issues found in the codebase." \
            --head $LINT_BRANCH \
            --base $BRANCH_NAME